"use strict";

module.exports = function()
{
	global.DEBUG = false;
	global.CPU_SAFETY_RATIO = 0.25;

	global.REQUIRED_BUCKET_FOR_LATE_TICK = 1000;

	global.IN_NOVICEAREA = false;

	global.NOVICEAREA_BOX =
		{ top: {half: SOUTH, distance: 86}
		, bottom: {half: SOUTH, distance: 89}
		, left: {half: WEST,  distance: 24}
		, right: {half: WEST,  distance: 21}
		};



	global.PRIORITIES = [];
	const makeRange = function(name, count, basePriority)
	{
		for(let index = 1; index <= count; index++)
			global.PRIORITIES[(name + "_" + index)] = basePriority + count - index;
	};

	global.PRIORITIES.SPAWN_RECOVERY_FILLER = 1200;
	global.PRIORITIES.SPAWN_RECOVERY_MINER = 1150;
	global.PRIORITIES.SPAWN_ENERGY_MINER = 1100;
	global.PRIORITIES.SPAWN_HAULER = 1000;
	global.PRIORITIES.SPAWN_FILLER = 950;
	global.PRIORITIES.SPAWN_ADHOC = 900;
	global.PRIORITIES.SPAWN_MINERAL_MINER = 800;
	global.PRIORITIES.SPAWN_BUILDER = 700;
	global.PRIORITIES.SPAWN_FIXER = 600;
	global.PRIORITIES.SPAWN_UPGRADER = 500;
	global.PRIORITIES.SPAWN_STORAGE_KEEPER = 450;
	global.PRIORITIES.SPAWN_OFFENSE = 400;
	global.PRIORITIES.SPAWN_EXPLORER = 300;

	makeRange("BUILD_EXTENSION_FIRST_FIVE", 60, 1100);
	global.PRIORITIES.BUILD_TOWER = 1000;
	global.PRIORITIES.BUILD_ADHOC = 950;
	global.PRIORITIES.BUILD_SPAWN = 900;
	global.PRIORITIES.BUILD_ENERGY_MINING_CONTAINER = 800;
	global.PRIORITIES.BUILD_FLOWER_CONTAINER = 700;
	global.PRIORITIES.BUILD_UPGRADER_CONTAINER = 600;
	global.PRIORITIES.BUILD_FLOWER_ROAD = 565;
	makeRange("BUILD_EXTENSION_AFTER_FIVE", 60, 500);
	global.PRIORITIES.BUILD_FLOWER_LINK = 400;
	global.PRIORITIES.BUILD_UPGRADER_LINK = 375;
	global.PRIORITIES.BUILD_ENERGY_MINING_LINK = 350;
	global.PRIORITIES.BUILD_MINERAL_MINING_CONTAINER = 200;
	global.PRIORITIES.BUILD_MINERAL_EXTRACTOR = 100;
	global.PRIORITIES.BUILD_STORAGE = 0;
	global.PRIORITIES.BUILD_STORAGE_LINK = -100;
	global.PRIORITIES.BUILD_TERMINAL = -200;
	global.PRIORITIES.BUILD_POWER_SPAWN = -300;
	global.PRIORITIES.BUILD_NUKER = -400;
	makeRange("BUILD_LAB", 10, -500);
	global.PRIORITIES.BUILD_STORAGE_ROAD = -600;

	global.PRIORITIES.RESOURCE_ADHOC = 1500;
	global.PRIORITIES.RESOURCE_FILLER = 1300;
	global.PRIORITIES.RESOURCE_UPGRADE = 1200;
	global.PRIORITIES.RESOURCE_STORAGE = 1100;
	global.PRIORITIES.RESOURCE_MINERAL = 1000;
	global.PRIORITIES.RESOURCE_DEFAULT = 1000;

	global.MY_USERNAME = "zigs";
};