"use strict";

module.exports = function()
{
	global.DEBUG = false;
	global.CPU_SAFETY_RATIO = 0.25;

	global.REQUIRED_BUCKET_FOR_LATE_TICK = 1000;

	global.IN_NOVICEAREA = false;

	global.NOVICEAREA_BOX =
		{ top: {half: SOUTH, distance: 86}
		, bottom: {half: SOUTH, distance: 89}
		, left: {half: WEST,  distance: 24}
		, right: {half: WEST,  distance: 21}
		};

	global.PRIORITIES =
		{ SPAWN_RECOVERY_FILLER: 1200
		, SPAWN_RECOVERY_MINER: 1150
		, SPAWN_ENERGY_MINER: 1100
		, SPAWN_HAULER: 1000
		, SPAWN_FILLER: 950
		, SPAWN_ADHOC: 900
		, SPAWN_MINERAL_MINER: 800
		, SPAWN_BUILDER: 700
		, SPAWN_FIXER: 600
		, SPAWN_UPGRADER: 500
		, SPAWN_STORAGE_KEEPER: 450
		, SPAWN_OFFENSE: 400
		, SPAWN_EXPLORER: 300

		, BUILD_EXTENSION_FIRST_FIVE: 1100
		, BUILD_TOWER: 1000
		, BUILD_ADHOC: 950
		, BUILD_SPAWN: 900
		, BUILD_ENERGY_MINING_CONTAINER: 800
		, BUILD_UPGRADER_CONTAINER: 700
		, BUILD_FLOWER_CONTAINER: 600
		, BUILD_FLOWER_ROAD: 550
		, BUILD_EXTENSION_AFTER_FIVE: 500
		, BUILD_FLOWER_LINK: 400
		, BUILD_UPGRADER_LINK: 375
		, BUILD_ENERGY_MINING_LINK: 350
		, BUILD_MINERAL_MINING_CONTAINER: 200
		, BUILD_MINERAL_EXTRACTOR: 100
		, BUILD_STORAGE: 0
		, BUILD_STORAGE_LINK: -100
		, BUILD_TERMINAL: -200
		, BUILD_POWER_SPAWN: -300
		, BUILD_NUKER: -400
		, BUILD_LAB: -500
		, BUILD_STORAGE_ROAD: -600

		, RESOURCE_ADHOC: 1500
		, RESOURCE_FILLER: 1300
		, RESOURCE_UPGRADE: 1200
		, RESOURCE_STORAGE: 1100
		, RESOURCE_MINERAL: 1000
		, RESOURCE_DEFAULT: 1000
		};

	global.MY_USERNAME = "zigs";
};